"""make user fields nullable

Revision ID: 2fff6f32a0b3
Revises: cce019417697
Create Date: 2025-04-22 23:58:16.469935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fff6f32a0b3'
down_revision: Union[str, None] = 'cce019417697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user', 'middle_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user', 'gender',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'gender',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user', 'middle_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
